name: firedart
description: A dart-native implementation of the Firebase Auth and Firestore SDKs.
version: 1.0.0-nullsafety
homepage: https://github.com/cachapa/firedart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.0
  grpc: ^3.0.0
  protobuf: ^2.0.0
  fixnum: ^1.0.0

dev_dependencies:
  test: ^1.15.4
  pedantic: ^1.9.2
